config/routes.rb
Rails.application.routes.draw do
  get 'flowers/index', to: "flowers#index"
#  get 'pages/home'
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/flowers/index.html.erb
<div id="flower-index">
    <div class="container">
      <div class="row justify-content-center m-5" >
        <div class="col-6" align="center">
           <div class="card" style="width: 18rem;">
              <img src="https://cdn.shopify.com/s/files/1/1095/8052/t/3/assets/logo.png?v=16319306062312551641" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text"> A family farm based Seed Company in SW Oregon growing Organic & Biodynamic since 1997.</p>
                <%= link_to " Go ", "https://www.siskiyouseeds.com/", class:"btn btn-primary" %>
  <!--                <a href="#" class="btn btn-primary">Go </a> -->
              </div>
          </div>
        </div>
        <div class="col-6" align="center">
           <div class="card" style="width: 18rem;">
              <img src=<%=asset_url("monika-grabkowska-small_unsplash.jpg")%> class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Vegetables</h5>
                <p class="card-text">Oregon vegetable seeds retailers</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
          </div>
        </div>
      </div>  
    </div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Garden life", root_path, class: "navbar-brand", id: "logo" %>  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Flowers", flowers_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
<!--    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>For the love of Gardening!</title>
  </head>
  <body>
      <section class="jumbotron text-center text-center text-white">
        <div class="container">
          <h1 class="jumbotron-heading display-3">For the love of Gardening</h1></br>
          <p class="lead">“No occupation is so delightful to me as the culture of the earth, no culture comparable to that of the garden...But though an old man, I am but a young gardener.”

― Thomas Jefferson</p>
        </div>
      </section>
    <section>
    <div class="container">
      <div class="row justify-content-center m-5" >
        <div class="col-6" align="center">
           <div class="card" style="width: 18rem;">
              <img src=<%=asset_url("tavin-dotson-dahlia-unsplash.jpg")%> class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Flowers</h5>
                <p class="card-text">Oregon flower seeds retailers</p>
                <%= link_to " Go ", flowers_index_path, class:"btn btn-primary" %>
  <!--                <a href="#" class="btn btn-primary">Go </a> -->
              </div>
          </div>
        </div>
        <div class="col-6" align="center">
           <div class="card" style="width: 18rem;">
              <img src=<%=asset_url("monika-grabkowska-small_unsplash.jpg")%> class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Vegetables</h5>
                <p class="card-text">Oregon vegetable seeds retailers</p>
                <a href="#" class="btn btn-primary">Go </a>
              </div>
          </div>
        </div>
      </div>  
    </div>
  </section>
  <footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Angela Tan", "https://www.linkedin.com/in/angelaitan/", class: "text-white" %></small>
    </div>
  </footer>    

    <!-- Optional JavaScript -->
  </body>
</html>